---
- name: Instaling Zabbix
  hosts: web-zabbix
  tasks:

    - name: Wget Repository Zabbix
      ansible.builtin.get_url:
        url: https://repo.zabbix.com/zabbix/6.0/rhel/8/x86_64/zabbix-release-6.0-4.el8.noarch.rpm
        dest: /home/ansible/
        mode: '0777'

    - name: Install .rpm package Zabbix
      ansible.builtin.yum:
        name: https://repo.zabbix.com/zabbix/6.0/rhel/8/x86_64/zabbix-release-6.0-4.el8.noarch.rpm
        state: present 

    - name: Install Components Zabbbix
      yum:
        name: "{{ packages }}"
        state: latest
      vars:
        packages:
        - zabbix-server-mysql 
        - zabbix-web-mysql
        - zabbix-sql-scripts 
        - zabbix-nginx-conf
        - zabbix-agent
        - mysql-server
        - zabbix-selinux-policy

    - name: start service MySQL
      service:
        name: mysqld
        state: started
        enabled: true

    - name: Create database and Commands config Zbx
      ansible.builtin.shell:
        cmd: "{{ item }}"
      loop:
        - mysql -u root --execute="create database zabbix character set utf8mb4 collate utf8mb4_bin;"
        - mysql -u root --execute="create user zabbix@192.168.32.131 identified by 'Teste#20';"
        - mysql -u root --execute="grant all privileges on zabbix.* to zabbix@192.168.32.131;"
        - mysql -u root --execute="set global log_bin_trust_function_creators = 1;"
        - sed -i s'/# DBPassword=/DBPassword=Julia#20/' /etc/zabbix/zabbix_server.conf
        - sed -i s'/# DBHost=localhost/DBHost=192.168.32.131/' /etc/zabbix/zabbix_server.conf
        - zcat /usr/share/zabbix-sql-scripts/mysql/server.sql.gz | mysql --default-character-set=utf8mb4 -h 192.168.32.131 -uzabbix -p'Teste#20' zabbix
        - mysql -u root --execute="set global log_bin_trust_function_creators = 0;"
        - sed -i s'/#        listen          8080;/        listen          80;/' /etc/nginx/conf.d/zabbix.conf
        - sed -i s'/#        server_name     example.com;/        server_name     192.168.32.131;/' /etc/nginx/conf.d/zabbix.conf

    - name: start service loop
      service:
        name: "{{ item }}"
        state: started
        enabled: true
      loop:
        - zabbix-agent
        - zabbix-server
        - nginx
        - php-fpm
